proxy:
  title: Open Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: archivists
  # Example: 'simple' authentication configuration
  users:
  - name: elizabeth.milford
    password: Welcome1
    groups: archivists
  - name: jarrod.harvey
    password: Welcome1
    groups: archivists
  # Example: 'simple' authentication configuration
  docker:
    cert-path: /home/none
    url: http://127.0.0.1:2375
    port-range-start: 20000
  specs:
  - id: RPEAT
    display-name: RecordPoint Export to Archivematica Transfer
    description: Upload a zip of an export from RecordPoint, and this app will turn it into an Archivematica Transfer
    container-cmd: ["R", "-e", "shiny::runApp('/root/RPEAT')"]
    container-image: rpeat
    container-log-path: ./container-logs
    # Make sure that there is a docker network to allow connection to the host!
    # docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dockernet
    container-network: dockernet
    access-groups: archivists
    container-volumes: [ "/home/RecordPoint_Transfers:/home/RecordPoint_Transfers" ] 

logging:
  file:
    shinyproxy.log

spring:
  servlet:
    multipart:
      max-file-size: 2999MB
      max-request-size: 2999MB
