proxy:
  title: Open Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  #port: 8080
  port: 8080
  authentication: simple
  admin-groups: archivists
  # Example: 'simple' authentication configuration
  users:
  - name: elizabeth.milford
    password: Welcome1
    groups: archivists
  - name: jarrod.harvey
    password: Welcome1
    groups: archivists
  - name: bill.mezzetti
    password: password
    groups: examiners
  - name: test.examiner
    password: password
    groups: examiners
 
  # Example: 'simple' authentication configuration
  docker:
    cert-path: /home/none
    url: http://127.0.0.1:2375
    port-range-start: 20000
  specs:
  - id: RPEAT
    display-name: RecordPoint Export to Archivematica Transfer
    description: Upload an export from RecordPoint, and this app will turn it into an Archivematica Transfer
    container-cmd: ["R", "-e", "shiny::runApp('/root/RPEAT')"]
    container-image: rpeat
    container-log-path: ./container-logs
    # Make sure that there is a docker network to allow connection to the host!
    # docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dockernet
    container-network: dockernet
    access-groups: archivists
    container-volumes: [ "/home/RecordPoint_Transfers:/home/RecordPoint_Transfers", "/mnt/RecordPoint_Exports:/mnt/RecordPoint_Exports"] 
    # The below container is included only to demonstrate the practice exam tool
  - id: Practice-Exam
    display-name: Practice Exam
    description: A tool that allows an examiner to audit a practice exam
    container-cmd: ["R", "-e", "shiny::runApp('/root/Practice_Exam_Tool')"]
    container-image: practiceexam
    access-groups: examiners
  - id: upload_archival_scans_to_archivematica
    display-name: Upload Archival Scans
    description: Upload scans (digitisations) of collections from the RACS Archives to Archivematica
    container-cmd: ["R", "-e", "shiny::runApp('/root/upload_archival_scans_to_archivematica')"]
    container-image: digitisations_and_donations
    access-groups: archivists
    container-volumes: [ "/home/Archival_Transfers:/home/Archival_Transfers" ]
    # container-volumes: [ "/opt/digitisations_and_donations/upload_archival_scans_to_archivematica/Inmagic_Dump:/root/digitisations_and_donations/upload_archival_scans_to_archivematica/Inmagic_Dump" ]
  - id: upload_donations_to_archivematica
    display-name: Upload Digital Donations
    description: Upload digital donations (such as CVs) that have been made to RACS
    container-cmd: ["R", "-e", "shiny::runApp('/root/upload_donations_to_archivematica')"]
    container-image: digitisations_and_donations
    access-groups: archivists
    container-volumes: [ "/home/Digital_Donations:/home/Digital_Donations" ]


logging:
  file:
    shinyproxy.log

spring:
  servlet:
    multipart:
      max-file-size: 2999MB
      max-request-size: 2999MB
